# Generated by Django 3.1 on 2020-09-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Dragon',
        ),
    ]
