# Generated by Django 3.1 on 2020-09-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_dragon_toys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('V', 'Village'), ('T', 'Town'), ('C', 'City')], default='V', max_length=1),
        ),
    ]
