# Generated by Django 3.1 on 2020-09-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200910_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('B', 'Village'), ('L', 'Town'), ('D', 'City')], default='B', max_length=1),
        ),
    ]
